// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: './src/database/prisma',
  migrations: {
    path: './src/database/prisma/migrations',
    seed: 'ts-node --project tsconfig.seed.json -r tsconfig-paths/register src/database/seed/index.ts',
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
